FROM alpine:edge
MAINTAINER Erin Schnabel <schnabel@us.ibm.com> (@ebullientworks)

ARG userId=1000
ARG groupId=1000

# Install chromium, node, vim, bash, ...
RUN apk add --no-cache \
      bash curl chromium nss freetype freetype-dev harfbuzz ca-certificates ttf-freefont \
      nodejs npm vim wget xvfb

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/xvfb-chromium
ENV CHROME_BIN=/usr/bin/xvfb-chromium
ENV HOME /app/node_modules/.home

COPY docker/docker-build.sh /usr/local/bin
COPY docker/xvfb-chromium /usr/bin/xvfb-chromium

RUN chmod +x /usr/local/bin/docker-build.sh /usr/bin/xvfb-chromium \
 && ln -s /usr/bin/xvfb-chromium /usr/bin/google-chrome \
 && echo 'export PATH=$PATH:/app/node_modules/.bin' >> /etc/bash.bashrc \
 && addgroup chrome \
 && adduser -H -D -s /bin/bash -u ${userId} -G chrome -h /app/node_modules/.home chrome \
 && addgroup chrome audio \
 && addgroup chrome video \
 && mkdir -p /app/node_modules \
 && chown -R ${userId}:${groupId} /app

WORKDIR /app
USER ${userId}

#Express port
EXPOSE 3000

#Grunt watch
EXPOSE 35729

CMD [ "echo", "To reach a shell for building, use ./build.sh shell" ]
