FROM node:10
MAINTAINER Erin Schnabel <schnabel@us.ibm.com> (@ebullientworks)

ARG userId=1000
ARG groupId=1000

ENV DEBIAN_FRONTEND noninteractive
ENV PHANTOMJS_VERSION 2.1.1
ENV HOME /app/node_modules/.home

RUN apt-get update \
  && apt-get install -y \
     bzip2 \
     curl  \
  && apt-get autoremove \
  && apt-get clean \
  && npm -g install npm \
  && rm -rf /tmp/* /var/lib/apt/lists/*

RUN mkdir /tmp/phantomjs \
  && curl -L https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 \
         | tar -xj --strip-components=1 -C /tmp/phantomjs \
  && cd /tmp/phantomjs \
  && mv bin/phantomjs /usr/local/bin \
  && echo 'export PATH=$PATH:/app/node_modules/.bin' >> /etc/bash.bashrc \
  && mkdir -p /app/node_modules \
  && chown -R ${userId}:${groupId} /app

WORKDIR /app

COPY docker/docker-build.sh /usr/local/bin
RUN chmod +x /usr/local/bin/docker-build.sh

#Express port
EXPOSE 3000

#Grunt watch
EXPOSE 35729

CMD [ "echo", "To reach a shell for building, use ./build.sh shell" ]
